[package]
name = "guessing-game"
version = "0.1.0"
edition = "2021"
authors = ["Alain D'Ettorre <alain.det@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.15"
